apiVersion: v1
kind: Service
metadata:
  name: KENUXA OPS
  labels:
    app: KENUXA OPS
spec:
  type: ClusterIP
  selector:
    app: KENUXA OPS
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
